replicaCount: 1

image:
  repository: quay-8rnsl.apps.cluster-8rnsl.8rnsl.sandbox2169.opentlc.com/nginx-demo/nginx-app-dev
  tag: "dd00a26b138017ca2001c6d010b7adffe3188137"
  pullPolicy: Always

imagePullSecrets:
  - name: quay-dev-pusher

service:
  port: 8080

route:
  enabled: true
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

probes:
  liveness:
    path: /
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    path: /
    initialDelaySeconds: 3
    periodSeconds: 5

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]
  seccompProfile:
    type: RuntimeDefault
