apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-dev
  namespace: janus-argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ranjithreddyt/redhat-demo.git
    targetRevision: main
    path: chart
    helm:
      valueFiles: [values.yaml, values-dev.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
