apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-stage
  namespace: janus-argocd
spec:
  project: default
  sources:
    - repoURL: quay-8rnsl.apps.cluster-8rnsl.8rnsl.sandbox2169.opentlc.com/nginx-demo
      chart: nginx-app
      targetRevision: 0.1.0
      helm:
        valueFiles:
          - $values/chart/values.yaml
          - $values/chart/values-stage.yaml
    - repoURL: https://github.com/ranjithreddyt/redhat-demo.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: app-stage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
